version: '3.8'

networks:
  networth:

volumes:
  db_users:

services:

  user-service:
    image: networth/user-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    networks:
      - networth
    healthcheck:
      test: "curl --fail --silent localhost:8081/q/health/ready | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      - users_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      QUARKUS_PROFILE: docker
      QUARKUS_APPLICATION_NAME: user-service
      DB_URL: jdbc:mysql://users_db:3306/usersdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER: admin
      DB_PASSWORD: password

  users_db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=usersdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - "3310:3306"
    networks:
      - networth
    volumes:
      - db_users:/var/lib/mysql
