version: '3.8'

networks:
  networth:

volumes:
  db_account:

services:

  account-service:
    image: networth/account-service:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    networks:
      - networth
    healthcheck:
      test: "curl --fail --silent localhost:8082/q/health/ready | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      - account_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      QUARKUS_PROFILE: docker
      QUARKUS_APPLICATION_NAME: account-service
      DB_URL: jdbc:mysql://account_db:3306/accountdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER: admin
      DB_PASSWORD: password

  account_db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=accountdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"
    networks:
      - networth
    volumes:
      - db_account:/var/lib/mysql
