version: '3.8'

networks:
  networth:

volumes:
  db_truelayer:

services:

  truelayer-service:
    image: networth/truelayer-service:0.0.1-SNAPSHOT
    ports:
      - "8084:8084"
    networks:
      - networth
    healthcheck:
      test: "curl --fail --silent localhost:8084/q/health/ready | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      - truelayer_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      QUARKUS_PROFILE: docker
      QUARKUS_APPLICATION_NAME: truelayer-service
      DB_URL: jdbc:mysql://truelayer_db:3306/truelayerdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER: admin
      DB_PASSWORD: password

  truelayer_db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=truelayerdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - "3309:3306"
    networks:
      - networth
    volumes:
      - db_truelayer:/var/lib/mysql
