---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: eurekaserver
      name: eurekaserver
    spec:
      ports:
        - name: http
          port: 80
          targetPort: 8761
      selector:
        app: eurekaserver
      type: ClusterIP
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: eurekaserver
      name: eurekaserver
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      labels:
        app: eurekaserver
      name: eurekaserver:view
    roleRef:
      kind: Role
      apiGroup: rbac.authorization.k8s.io
      name: namespace-reader
    subjects:
      - kind: ServiceAccount
        name: eurekaserver
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      namespace: default
      name: namespace-reader
    rules:
      - apiGroups: ["", "extensions", "apps"]
        resources: ["services", "endpoints", "pods"]
        verbs: ["get", "list", "watch"]
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: eurekaserver-deployment
    spec:
      selector:
        matchLabels:
          app: eurekaserver
      template:
        metadata:
          labels:
            app: eurekaserver
        spec:
          serviceAccount: eurekaserver
          containers:
            - name: eurekaserver
              image: networth/eurekaserver:0.0.1-SNAPSHOT
              imagePullPolicy: IfNotPresent
              readinessProbe:
                httpGet:
                  port: 8761
                  path: /q/health/ready
                initialDelaySeconds: 100
                periodSeconds: 30
              livenessProbe:
                httpGet:
                  port: 8761
                  path: /q/health/live
                initialDelaySeconds: 100
                periodSeconds: 30
              ports:
                - containerPort: 8761
